# Generated by Django 3.1.7 on 2021-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(max_length=64, unique=True)),
                ('pub_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=64, unique=True)),
                ('book_name', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('pub_date', models.CharField(max_length=32)),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.publisher')),
            ],
        ),
    ]
